spring:
  datasource:
    url: jdbc:mysql://121.4.208.247:3306/spring_security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Judge@1024
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80
  servlet:
    context-path: /spring-security